# import key
- name: import key
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Installing from the APT repositoryedit
  shell: sudo apt-get install apt-transport-https

- name: Save the repository definition
  shell: echo "deb https://artifacts.elastic.co/packages/oss-{{elasticsearch_meta[elasticsearch_version].yum_name}}/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{{elasticsearch_meta[elasticsearch_version].yum_name}}.list

- name: install elasticsearch
  shell: sudo apt-get update && sudo apt-get install elasticsearch-oss-{{elasticsearch_meta[elasticsearch_version].yum_pkg_name_debian}} -y

- name: install kibana
  shell: sudo apt-get update && sudo apt-get install kibana-{{elasticsearch_meta[elasticsearch_version].yum_pkg_name_debian}} -y
  when: elasticsearch_install_kibana