- name: import key
  shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- set_fact: version_package="{{elasticsearch_meta[elasticsearch_version].yum_name}}"

- name: Setting elasticsearch and kibana source
  template:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: Install elasticsearch
  shell: sudo yum install elasticsearch-oss-{{elasticsearch_meta[elasticsearch_version].yum_pkg_name_redhat}} -y
  
- name: Install kibana
  shell: sudo yum install kibana-oss-{{elasticsearch_meta[elasticsearch_version].yum_pkg_name_redhat}} -y 
  when: elasticsearch_install_kibana
